version: '3.10'

services:
  ocr-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: firstyarus-ocr-api
    container_name: firstyarus-ocr-api
    ports:
      - "8004:8000"
    restart: unless-stopped


